// Login
export const ACTION_LOGIN_START = "ACTION_LOGIN_START";
export const ACTION_LOGIN_CANCEL = "ACTION_LOGIN_CANCEL";
export const ACTION_LOGIN_SUCCESS = "ACTION_LOGIN_SUCCESS";
export const ACTION_LOGIN_ERROR = "ACTION_LOGIN_ERROR";

// Register
export const ACTION_REGISTER_START = "ACTION_REGISTER_START";
export const ACTION_REGISTER_CANCEL = "ACTION_REGISTER_CANCEL";
export const ACTION_REGISTER_SUCCESS = "ACTION_REGISTER_SUCCESS";
export const ACTION_REGISTER_ERROR = "ACTION_REGISTER_ERROR";


