const todoActions = {
  ADD_LIST: "TRELLO/ADD_LIST",
  CHANGE_TITLE_LIST: "TRELLO/CHANGE_TITLE_LIST",
  REMOVE_LIST: "TRELLO/REMOVE_LIST",

  ADD_CARD: "TRELLO/ADD_CARD",
  REMOVE_CARD: "TRELLO/REMOVE_CARD",
  EDIT_CARD: "TRELLO/EDIT_CARD",

  DRAG_END_LIST: "TRELLO/DRAG_END_LIST",
  DRAG_END_CARD: "TRELLO/DRAG_END_CARD",
};

export default todoActions;
