// User
const UserActionTypes = {
  SET_CURRENT_USER_SUCCESS: "SET_CURRENT_USER_SUCCESS",
  SET_CURRENT_USER_FAILURE: "SET_CURRENT_USER_FAILURE",

  ACTION_LOGIN_START: "ACTION_LOGIN_START",
  ACTION_LOGIN_CANCEL: "ACTION_LOGIN_CANCEL",
  ACTION_LOGIN_SUCCESS: "ACTION_LOGIN_SUCCESS",
  ACTION_LOGIN_ERROR: "ACTION_LOGIN_ERROR",

  ACTION_REGISTER_START: "ACTION_REGISTER_START",
  ACTION_REGISTER_CANCEL: "ACTION_REGISTER_CANCEL",
  ACTION_REGISTER_SUCCESS: "ACTION_REGISTER_SUCCESS",
  ACTION_REGISTER_ERROR: "ACTION_REGISTER_ERROR",

  ACTION_UPDATE_USER_PROFILE: "ACTION_UPDATE_USER_PROFILE",

  ACTION_USER_LOGOUT: "ACTION_USER_LOGOUT"
};

export default UserActionTypes;
